name: Parse Resume Manually

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab in GitHub

jobs:
  parse_resume_job:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Checks out your code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # You can change this to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found. Please create one with necessary packages."
            # Optionally, install known dependencies directly if requirements.txt is missing
            # pip install pdfplumber google-generativeai supabase
            exit 1
          fi

      - name: Run resume parser script
        env:
          GEMINI_FIRST_API_KEY: ${{ secrets.GEMINI_FIRST_API_KEY }} # Uses a GitHub secret for the API key
        run: python resume_parser.py
